CC_FLAGS := '-I /opt/homebrew/include \
    -L /opt/homebrew/lib \
    -lSDL2 \
    -W \
    -Wall \
    -Wextra \
    -g'

run-client: build-client
    ./client 127.0.0.1 6060

build-client:
    clang client.c dynarr.c dict.c -o client {{CC_FLAGS}}

# build-dynarr:
#     clang -c dynarr.c -o dynarr.o {{CC_FLAGS}} 

clean:
    rm client || true 
    rm server || true 