PORT := '6060'

CC_FLAGS := '-W \
    -Wall \
    -Wextra \
    -g'

run-client: build-client
    ./client 127.0.0.1 {{PORT}}

build-client:
    clang client.c DynArr/dynarr.c Dict/dict.c utils.c -o client -lSDL2 {{CC_FLAGS}} \
    -I /opt/homebrew/include \
    -L /opt/homebrew/lib \

run-server: build-server
    ./server {{PORT}}

build-server:
    clang server.c utils.c DynArr/dynarr.c Dict/dict.c -o server {{CC_FLAGS}} 

clean:
    rm client || true 
    rm server || true 
