PORT := '6060'

CC_FLAGS := '-W \
    -Wall \
    -Wextra \
    -g'

INCLUDE_ALL := 'DynArr/dynarr.c Dict/dict.c utils.c Types/idot.c Types/iline.c Types/floatx.c Types/header.c'

run-client: build-client
    ./client 127.0.0.1 {{PORT}}

build-client:
    clang client.c -o client -lSDL2 {{CC_FLAGS}} {{INCLUDE_ALL}} \
    -I /opt/homebrew/include \
    -L /opt/homebrew/lib \

run-server: build-server
    ./server {{PORT}}

build-server:
    clang server.c {{INCLUDE_ALL}} -o server {{CC_FLAGS}}

run-tests: build-tests
    ./test

build-tests:
    clang Tests/test.c {{INCLUDE_ALL}} {{CC_FLAGS}} -o test

clean:
    rm client || true 
    rm server || true 
